/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cmzw (https://sketchfab.com/cmzw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-planet-789725db86f547fc9163b00f302c3e70
Title: Stylized planet
*/

import { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import planetScene from '../assets/3d/stylized_planet.glb';

const Planet = (props) => {
  const planetRef = useRef();

  const { nodes, materials } = useGLTF(planetScene);

  return (
    <a.group ref={planetRef} {...props}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Clouds}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Planet}
      />
    </a.group>
  );
}

export default Planet;